### ISSUE TITLE
Database Setup

### ISSUE THREAD

**Issue by jazahn** [Harvard-ATG/Policy-Wizard#1]
Set up the database.

table POLICIES

```
ID
NAME
EXTERNAL_ID (topicId)
STATUS (published, unpublished)
PUBLISHED_BY varchar2 (huid)
PUBLISH_DATE timestamp
BODY (text)
```

We could put the boilerplates in this table and reference them directly in the code.  i.e. POLICIES->ID 1, 2, 3 would be the three boilerplates.
- probably should be mysql to avoid clob issues
- get pankaj to init at least a dev and a prod

**Comment by arthurian** [comment]
I think we have two basic approaches to choose from:

1) One-table solution. Boilerplates can either be stored at IDs 1-4 so they can be edited in the database or they can simply be hard coded into the application via smarty templates or some other method. 

```
POLICIES
id
name - name of the policy, for boilerplates this is what is shown on the UI
body - policy text
external_id - topic id reported by isites 
published_by - user id reported by isites when published
is_published - 1 if published, 0 otherwise (defaults to 0)
publish_date 
```
- Pros: Simple, self-contained, only one table to deal with.
- Cons: Have to hard code the boilerplate text or references to them in the code.

2) Two-table solution. Boilerplates are stored in the database separately from published policies. 

```
POLICIES
id
external_id - topic id reported by isites 
body - policy text
published_by - user id reported by isites when published
is_published - 1 if published, 0 otherwise (defaults to 0)
publish_date

POLICY_TEMPLATES
id
name - name of the policy, displayed on UI
body - policy text
sort_order - a number used to order the policies
is_active - 1 if active, 0 otherwise (defaults to 0)
```
- Pros: Clearly separates boilerplates from the actual policies that have been saved/published, easier to add/remove policy templates, can pull the list of policy options straight from the table.
- Cons: More complex, instructions text would still need to be hard coded in the application (or else add that to the database too).

I think the second option would be nice if we have time, but given the time crunch, the first would be much faster.

**Comment by jazahn** [comment]
I can proceed with using sqlite for development -- dev-mysql.fas is having issues.  I think running yii's migrate on it broked it.

Migration scripts are set. DB is functional as SQLite.

Not closing this issue until mysql is working.
