### ISSUE TITLE
Canceling a policy should return to list of policies

### ISSUE THREAD

**Issue by arthurian** [Harvard-ATG/Policy-Wizard#31]
When you cancel policy changes you should be redirected back to the list of policies. Currently, you are redirected to the _Unconfigured_ screen.

**Comment by jazahn** [comment]
if you want to go back you can click back, if you're canceling, you should be redirected all the way back to the resting state.  That's how other multi-page forms work, right?  Going cancel on page 3 of a multipage form doesn't send you to page 2, it cancels the form.
