### ISSUE TITLE
Save as draft confusing when a policy is published

### ISSUE THREAD

**Issue by arthurian** [Harvard-ATG/Policy-Wizard#32]
When a policy has already been published and a user goes to edit the policy, the behavior of the _Save as Draft_ vs _Publish_ button is confusing. The expected behavior is that if you click _Save as Draft_, the changes will _not_ be immediately published. This is not the case. The primary difference is that _Publish_ saves and redirects while _Save as Draft_ only saves. 

Removing the _Save as Draft_ button would be the simplest way to eliminate the confusion

**Comment by jazahn** [comment]
confusing to a fool. removing bug label
