### ISSUE TITLE
Make the TinyMCE font size bigger

### ISSUE THREAD

**Issue by arthurian** [Harvard-ATG/Policy-Wizard#37]
In order to change the default TinyMCE font size (11px), you have to create a custom CSS file and pass it to TinyMCE when it is initialized. This will override the default theme/css which is applied to the iframe content.

See this documentation on the TinyMCE wiki for more details:
- http://www.tinymce.com/wiki.php/Configuration:content_css

Or this Q&A on Stackoverflow:
- http://stackoverflow.com/questions/4427407/how-to-change-default-font-size-in-tinymce

**Comment by jazahn** [comment]
This is why I'm against using tinymce.
